### ISSUE TITLE
Chat messeages (from this mod and AlchemistNPC) do not auto-disapear 

### ISSUE THREAD

**Issue by Zemogiter** [nakano15/giantsummon#1]
The mod makes the game enter a weird state where aforemoentioned glitch occurs and also fluids don't flow when the blocks around them are broken, they stay in palce. Also summoning Wall of Flesh by throwing Guide Doll into the lava dosen't work (the doll gets destroyed but WoF does not spawn). Disabling TerraGuardians fixes this.
Log file:
[client.log](https://github.com/nakano15/giantsummon/files/6951264/client.log)
World files for replicating the bug:
[Worlds.zip](https://github.com/nakano15/giantsummon/files/6951265/Worlds.zip)

**Comment by nakano15** [comment]
That's happening on the latest version of the mod?

**Comment by Zemogiter** [comment]
Yes

**Comment by nakano15** [comment]
Well, that freaking bug is still happening then.
I will investigate further to try banishing that issue for once and for all.

**Comment by Zemogiter** [comment]
I've also noticed that this mod now breaks the VeinMiner function (breaking ore blocks while holding the VM button dosen't work at all). This may help you to narrow down the cause of this bug. Also the mod sometimes causes the game to crash when reloading mods:
https://github.com/tModLoader/tModLoader/issues/1633

**Comment by nakano15** [comment]
I forgot to post here after launching the update. Did the issue you were happening disappear?

**Comment by Zemogiter** [comment]
Yes it did. Thanks.
